package uz.yalla.sdk.android.design.color

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// Generated by yalla-design. Do not edit manually.

// region Light Theme Colors

internal val LightTextBase = Color(0xFF101828)
internal val LightTextSubtle = Color(0xFF98A2B3)
internal val LightTextLink = Color(0xFF562DF8)
internal val LightTextRed = Color(0xFFF42500)
internal val LightTextWhite = Color(0xFFFFFFFF)
internal val LightBackgroundBase = Color(0xFFFFFFFF)
internal val LightBackgroundBrandBase = Color(0xFF562DF8)
internal val LightBackgroundSecondary = Color(0xFFF7F7F7)
internal val LightBackgroundTertiary = Color(0xFFE9EAEA)
internal val LightBorderDisabled = Color(0xFFE4E7EC)
internal val LightBorderFilled = Color(0xFF101828)
internal val LightBorderWhite = Color(0xFFFFFFFF)
internal val LightBorderError = Color(0xFFF42500)
internal val LightButtonActive = Color(0xFF562DF8)
internal val LightButtonDisabled = Color(0xFFC8CBFA)
internal val LightButtonSecondary = Color(0xFFF7F7F7)
internal val LightButtonTertiary = Color(0xFF101828)
internal val LightButtonDisabledTertiary = Color(0xFFCBD2E1)
internal val LightIconWhite = Color(0xFFFFFFFF)
internal val LightIconBase = Color(0xFF101828)
internal val LightIconSecondary = Color(0xFF562DF8)
internal val LightIconDisabled = Color(0xFFC8CBFA)
internal val LightIconRed = Color(0xFFF42500)
internal val LightIconSubtle = Color(0xFF98A2B3)

// endregion

// region Dark Theme Colors

internal val DarkTextBase = Color(0xFFFFFFFF)
internal val DarkTextSubtle = Color(0xFF747C8B)
internal val DarkTextLink = Color(0xFF562DF8)
internal val DarkTextRed = Color(0xFFF42500)
internal val DarkTextWhite = Color(0xFFFFFFFF)
internal val DarkBackgroundBase = Color(0xFF1A1A20)
internal val DarkBackgroundBrandBase = Color(0xFF562DF8)
internal val DarkBackgroundSecondary = Color(0xFF21222B)
internal val DarkBackgroundTertiary = Color(0xFF1D1D26)
internal val DarkBorderDisabled = Color(0xFF383843)
internal val DarkBorderFilled = Color(0xFFFFFFFF)
internal val DarkBorderWhite = Color(0xFFFFFFFF)
internal val DarkBorderError = Color(0xFFF42500)
internal val DarkButtonActive = Color(0xFF562DF8)
internal val DarkButtonDisabled = Color(0xFF2C2D34)
internal val DarkButtonSecondary = Color(0xFFF7F7F7)
internal val DarkButtonTertiary = Color(0xFFFFFFFF)
internal val DarkButtonDisabledTertiary = Color(0xFFCBD2E1)
internal val DarkIconWhite = Color(0xFFFFFFFF)
internal val DarkIconBase = Color(0xFFFFFFFF)
internal val DarkIconSecondary = Color(0xFF562DF8)
internal val DarkIconDisabled = Color(0xFF2C2D34)
internal val DarkIconRed = Color(0xFFF42500)
internal val DarkIconSubtle = Color(0xFF98A2B3)

// endregion

// region Accent Colors

internal val PinkSun = Color(0xFFFF234B)
internal val Color1 = Color(0xFFFFD1D2)
internal val Color2 = Color(0xFFCADDFF)
internal val Color3 = Color(0xFFFFDFAB)
internal val Color4 = Color(0xFFA7FFF9)
internal val Color5 = Color(0xFFD6C8FF)

// endregion

// region Gradients

internal val SplashBackground = Brush.linearGradient(
    colors = listOf(Color(0xFF7957FF), Color(0xFF562DF8), Color(0xFF3812CE)),
    start = Offset(0f, 0f),
    end = Offset(1000f, 1000f)
)
internal val SunsetNight = Brush.linearGradient(listOf(Color(0xFFFF234B), Color(0xFF2F00EC)))

// endregion
