package uz.yalla.design.color

import androidx.compose.ui.graphics.Color

// Light mode colors

internal val light_text_base = Color(0xFF101828)
internal val light_text_subtle = Color(0xFF98A2B3)
internal val light_text_link = Color(0xFF562DF8)
internal val light_text_red = Color(0xFFF42500)
internal val light_text_white = Color(0xFFFFFFFF)
internal val light_background_base = Color(0xFFFFFFFF)
internal val light_background_brand = Color(0xFF562DF8)
internal val light_background_secondary = Color(0xFFF7F7F7)
internal val light_background_tertiary = Color(0xFFE9EAEA)
internal val light_border_disabled = Color(0xFFE4E7EC)
internal val light_border_filled = Color(0xFF101828)
internal val light_border_white = Color(0xFFFFFFFF)
internal val light_border_error = Color(0xFFF42500)
internal val light_button_active = Color(0xFF562DF8)
internal val light_button_disabled = Color(0xFFC8CBFA)
internal val light_button_secondary = Color(0xFFF7F7F7)
internal val light_button_tertiary = Color(0xFF101828)
internal val light_button_disabled_tertiary = Color(0xFFCBD2E1)
internal val light_icon_white = Color(0xFFFFFFFF)
internal val light_icon_base = Color(0xFF101828)
internal val light_icon_secondary = Color(0xFF562DF8)
internal val light_icon_disabled = Color(0xFFC8CBFA)
internal val light_icon_red = Color(0xFFF42500)
internal val light_icon_subtle = Color(0xFF98A2B3)
internal val accent_pink_sun = Color(0xFFFF234B)
internal val accent_color1 = Color(0xFFFFD1D2)
internal val accent_color2 = Color(0xFFCADDFF)
internal val accent_color3 = Color(0xFFFFDFAB)
internal val accent_color4 = Color(0xFFA7FFF9)
internal val accent_color5 = Color(0xFFD6C8FF)
internal val gradient_splash_0 = Color(0xFF7957FF)
internal val gradient_splash_1 = Color(0xFF562DF8)
internal val gradient_splash_2 = Color(0xFF3812CE)
internal val gradient_sunset_night_0 = Color(0xFFFF234B)
internal val gradient_sunset_night_1 = Color(0xFF2F00EC)
