package uz.yalla.sdk.android.design.font

import androidx.compose.runtime.Composable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.sp
import uz.yalla.sdk.android.design.R

// Generated by yalla-design. Do not edit manually.

@Composable
fun rememberFontScheme(): FontScheme {
    val normalFont = FontFamily(Font(R.font.roboto_normal))
    val mediumFont = FontFamily(Font(R.font.roboto_medium))
    val boldFont = FontFamily(Font(R.font.roboto_bold))

    return FontScheme(
        title =
            FontScheme.Title(
                xLarge = TextStyle(fontSize = 30.sp, lineHeight = 30.sp, fontFamily = boldFont),
                large = TextStyle(fontSize = 22.sp, lineHeight = 22.sp, fontFamily = boldFont),
                base = TextStyle(fontSize = 20.sp, lineHeight = 20.sp, fontFamily = boldFont)
            ),
        body =
            FontScheme.Body(
                caption = TextStyle(fontSize = 13.sp, lineHeight = 15.6.sp, fontFamily = mediumFont),
                large =
                    FontScheme.Body.Weighty(
                        regular = TextStyle(fontSize = 18.sp, lineHeight = 21.6.sp, fontFamily = normalFont),
                        medium = TextStyle(fontSize = 18.sp, lineHeight = 21.6.sp, fontFamily = mediumFont),
                        bold = TextStyle(fontSize = 18.sp, lineHeight = 21.6.sp, fontFamily = boldFont)
                    ),
                base =
                    FontScheme.Body.Weighty(
                        regular = TextStyle(fontSize = 16.sp, lineHeight = 20.8.sp, fontFamily = normalFont),
                        medium = TextStyle(fontSize = 16.sp, lineHeight = 20.8.sp, fontFamily = mediumFont),
                        bold = TextStyle(fontSize = 16.sp, lineHeight = 20.8.sp, fontFamily = boldFont)
                    ),
                small =
                    FontScheme.Body.Weighty(
                        regular = TextStyle(fontSize = 14.sp, lineHeight = 15.4.sp, fontFamily = normalFont),
                        medium = TextStyle(fontSize = 14.sp, lineHeight = 15.4.sp, fontFamily = mediumFont),
                        bold = TextStyle(fontSize = 14.sp, lineHeight = 15.4.sp, fontFamily = boldFont)
                    )
            ),
        custom =
            FontScheme.Custom(
                carNumber = TextStyle(fontSize = 12.sp, lineHeight = 16.sp, fontFamily = FontFamily(Font(R.font.nummernschild)))
            )
    )
}
